name: Broken Site Report
description: Help us improve UltimaDark by reporting a site that is broken in a new way on a supported desktop browser.
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Please do not remove or skip any part of this template
      description: All fields are required for a helpful report.
      options:
        - label: I understand that skipping or removing required fields may result in my issue being closed or blocked.
          required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Quick Checklist
      description: |
        Before submitting, please make sure you have completed all of the following steps:
      options:
        - label: I am using a compatible desktop browser that is up-to-date, or listed as compatible in the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md).
          required: true
        - label: I am reporting a genuinely new issue, not something that belongs in [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6), [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7), [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8), or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94).
          required: true
        - label: This site is not already listed in an open or closed issue, or in the issues above.
          required: true
        - label: I am using the latest version of UltimaDark.
          required: true
        - label: I have checked that ImageEdition, Caching, Service Worker Compatibility, and the extension itself are all enabled. I have also reloaded the site in a new tab, or flushed it with [Tab Suspender](https://www.github.com/Hau-Hau/firefox-tab-suspender).
          required: true
        - label: I tried disabling caching and refreshed the page several times, but the problem persists.
          required: true
        - label: The site is not on my excluded sites list, nor is it a protected domain.
          required: true
        - label: I have searched [known issues](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues), including closed ones, to avoid posting a duplicate.
          required: true
        - label: I have read the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md) and understand how to open a helpful issue.
          required: true
  - type: textarea
    id: url
    attributes:
      label: Site URL
      placeholder: www.example.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a description of what about the site is broken and attach screenshots at the bottom
      placeholder: Provide as much detail about the problem as you can and suggest solutions if you have one. 
    validations:
      required: true
  - type: checkboxes
    id: verbose
    attributes:
      label: Provide console logs 
      options:
        - label: Go to about:debugging#/runtime/this-firefox
          required: false
        - label: Click "Inspect" on UltimaDark
          required: false
        - label: Clear the log and refresh the page that is broken
          required: false
        - label: Copy the WHOLE output and insert it below
          required: false
  - type: textarea
    id: log
    attributes:
      label: Console Log or Error Output
      description: |
        Please copy and paste any output from the browser console or extension log that seems unusual, denotes a problem, or looks related to your issue—even if it's not an obvious error. This could be an error, a warning, or just something that stands out.
        You do not need to paste the entire log—just the lines that seem connected to the problem (errors, warnings, or anything mentioning UltimaDark or the site).
      placeholder: |
        Example:
        Error: Failed to apply dark mode on example.com background.js:2620:15
        Warning: Disconnected from tab example.com
        Set [] background.js:502:21
         ...more relevant lines...
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > ### GitHub is experiencing a high volume of malicious spam comments.
        > ### If you receive any replies asking you download a file, do NOT follow the download links!
        >
        > Note that this issue may be temporarily locked as an anti-spam measure after it is opened.
